//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proektirovanie2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Гот продукция.
    /// </summary>
    // *** Start programmer edit section *** (ГотПродукция CustomAttributes)

    // *** End programmer edit section *** (ГотПродукция CustomAttributes)
    [AutoAltered()]
    [Caption("Гот продукция")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ГотПродукцияE", new string[] {
            "Товар as \'Товар\'",
            "КолВо as \'Кол во\'",
            "Одобрено as \'Одобрено\'"})]
    public class ГотПродукция : ICSSoft.STORMNET.DataObject
    {
        
        private string fТовар;
        
        private string fКолВо;
        
        private bool fОдобрено;
        
        private IIS.Proektirovanie2.Номенклатура fНоменклатура;
        
        // *** Start programmer edit section *** (ГотПродукция CustomMembers)

        // *** End programmer edit section *** (ГотПродукция CustomMembers)

        
        /// <summary>
        /// КолВо.
        /// </summary>
        // *** Start programmer edit section *** (ГотПродукция.КолВо CustomAttributes)

        // *** End programmer edit section *** (ГотПродукция.КолВо CustomAttributes)
        [StrLen(255)]
        public virtual string КолВо
        {
            get
            {
                // *** Start programmer edit section *** (ГотПродукция.КолВо Get start)

                // *** End programmer edit section *** (ГотПродукция.КолВо Get start)
                string result = this.fКолВо;
                // *** Start programmer edit section *** (ГотПродукция.КолВо Get end)

                // *** End programmer edit section *** (ГотПродукция.КолВо Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ГотПродукция.КолВо Set start)

                // *** End programmer edit section *** (ГотПродукция.КолВо Set start)
                this.fКолВо = value;
                // *** Start programmer edit section *** (ГотПродукция.КолВо Set end)

                // *** End programmer edit section *** (ГотПродукция.КолВо Set end)
            }
        }
        
        /// <summary>
        /// Одобрено.
        /// </summary>
        // *** Start programmer edit section *** (ГотПродукция.Одобрено CustomAttributes)

        // *** End programmer edit section *** (ГотПродукция.Одобрено CustomAttributes)
        public virtual bool Одобрено
        {
            get
            {
                // *** Start programmer edit section *** (ГотПродукция.Одобрено Get start)

                // *** End programmer edit section *** (ГотПродукция.Одобрено Get start)
                bool result = this.fОдобрено;
                // *** Start programmer edit section *** (ГотПродукция.Одобрено Get end)

                // *** End programmer edit section *** (ГотПродукция.Одобрено Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ГотПродукция.Одобрено Set start)

                // *** End programmer edit section *** (ГотПродукция.Одобрено Set start)
                this.fОдобрено = value;
                // *** Start programmer edit section *** (ГотПродукция.Одобрено Set end)

                // *** End programmer edit section *** (ГотПродукция.Одобрено Set end)
            }
        }
        
        /// <summary>
        /// Товар.
        /// </summary>
        // *** Start programmer edit section *** (ГотПродукция.Товар CustomAttributes)

        // *** End programmer edit section *** (ГотПродукция.Товар CustomAttributes)
        [StrLen(255)]
        public virtual string Товар
        {
            get
            {
                // *** Start programmer edit section *** (ГотПродукция.Товар Get start)

                // *** End programmer edit section *** (ГотПродукция.Товар Get start)
                string result = this.fТовар;
                // *** Start programmer edit section *** (ГотПродукция.Товар Get end)

                // *** End programmer edit section *** (ГотПродукция.Товар Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ГотПродукция.Товар Set start)

                // *** End programmer edit section *** (ГотПродукция.Товар Set start)
                this.fТовар = value;
                // *** Start programmer edit section *** (ГотПродукция.Товар Set end)

                // *** End programmer edit section *** (ГотПродукция.Товар Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Proektirovanie2.Номенклатура.
        /// </summary>
        // *** Start programmer edit section *** (ГотПродукция.Номенклатура CustomAttributes)

        // *** End programmer edit section *** (ГотПродукция.Номенклатура CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Номенклатура"})]
        public virtual IIS.Proektirovanie2.Номенклатура Номенклатура
        {
            get
            {
                // *** Start programmer edit section *** (ГотПродукция.Номенклатура Get start)

                // *** End programmer edit section *** (ГотПродукция.Номенклатура Get start)
                IIS.Proektirovanie2.Номенклатура result = this.fНоменклатура;
                // *** Start programmer edit section *** (ГотПродукция.Номенклатура Get end)

                // *** End programmer edit section *** (ГотПродукция.Номенклатура Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ГотПродукция.Номенклатура Set start)

                // *** End programmer edit section *** (ГотПродукция.Номенклатура Set start)
                this.fНоменклатура = value;
                // *** Start programmer edit section *** (ГотПродукция.Номенклатура Set end)

                // *** End programmer edit section *** (ГотПродукция.Номенклатура Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ГотПродукцияE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ГотПродукцияE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ГотПродукцияE", typeof(IIS.Proektirovanie2.ГотПродукция));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ГотПродукция.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfГотПродукция CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfГотПродукция CustomAttributes)
    public class DetailArrayOfГотПродукция : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Proektirovanie2.DetailArrayOfГотПродукция members)

        // *** End programmer edit section *** (IIS.Proektirovanie2.DetailArrayOfГотПродукция members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ГотПродукция by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ГотПродукция.
        /// </summary>
        public DetailArrayOfГотПродукция(IIS.Proektirovanie2.Номенклатура fНоменклатура) : 
                base(typeof(ГотПродукция), ((ICSSoft.STORMNET.DataObject)(fНоменклатура)))
        {
        }
        
        public IIS.Proektirovanie2.ГотПродукция this[int index]
        {
            get
            {
                return ((IIS.Proektirovanie2.ГотПродукция)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Proektirovanie2.ГотПродукция dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
