//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proektirovanie2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Номенклатура.
    /// </summary>
    // *** Start programmer edit section *** (Номенклатура CustomAttributes)

    // *** End programmer edit section *** (Номенклатура CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("НоменклатураE", new string[] {
            "Наименование as \'Наименование\'",
            "ЕдИзм as \'Ед изм\'",
            "ЭкоКласс as \'Эко класс\'",
            "ЗащСвойст as \'Защ свойст\'"})]
    [AssociatedDetailViewAttribute("НоменклатураE", "ГотПродукция", "ГотПродукцияE", true, "", "Гот продукция", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("НоменклатураE", "ЗапасМатериалов", "ЗапасМатериаловE", true, "", "Запас материалов", true, new string[] {
            ""})]
    [View("НоменклатураL", new string[] {
            "Наименование as \'Наименование\'",
            "ЕдИзм as \'Ед изм\'",
            "ЭкоКласс as \'Эко класс\'",
            "ЗащСвойст as \'Защ свойст\'"})]
    public class Номенклатура : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаименование;
        
        private string fЕдИзм;
        
        private string fЭкоКласс;
        
        private string fЗащСвойст;
        
        private IIS.Proektirovanie2.DetailArrayOfГотПродукция fГотПродукция;
        
        private IIS.Proektirovanie2.DetailArrayOfЗапасМатериалов fЗапасМатериалов;
        
        // *** Start programmer edit section *** (Номенклатура CustomMembers)

        // *** End programmer edit section *** (Номенклатура CustomMembers)

        
        /// <summary>
        /// ЕдИзм.
        /// </summary>
        // *** Start programmer edit section *** (Номенклатура.ЕдИзм CustomAttributes)

        // *** End programmer edit section *** (Номенклатура.ЕдИзм CustomAttributes)
        [StrLen(255)]
        public virtual string ЕдИзм
        {
            get
            {
                // *** Start programmer edit section *** (Номенклатура.ЕдИзм Get start)

                // *** End programmer edit section *** (Номенклатура.ЕдИзм Get start)
                string result = this.fЕдИзм;
                // *** Start programmer edit section *** (Номенклатура.ЕдИзм Get end)

                // *** End programmer edit section *** (Номенклатура.ЕдИзм Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Номенклатура.ЕдИзм Set start)

                // *** End programmer edit section *** (Номенклатура.ЕдИзм Set start)
                this.fЕдИзм = value;
                // *** Start programmer edit section *** (Номенклатура.ЕдИзм Set end)

                // *** End programmer edit section *** (Номенклатура.ЕдИзм Set end)
            }
        }
        
        /// <summary>
        /// ЗащСвойст.
        /// </summary>
        // *** Start programmer edit section *** (Номенклатура.ЗащСвойст CustomAttributes)

        // *** End programmer edit section *** (Номенклатура.ЗащСвойст CustomAttributes)
        [StrLen(255)]
        public virtual string ЗащСвойст
        {
            get
            {
                // *** Start programmer edit section *** (Номенклатура.ЗащСвойст Get start)

                // *** End programmer edit section *** (Номенклатура.ЗащСвойст Get start)
                string result = this.fЗащСвойст;
                // *** Start programmer edit section *** (Номенклатура.ЗащСвойст Get end)

                // *** End programmer edit section *** (Номенклатура.ЗащСвойст Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Номенклатура.ЗащСвойст Set start)

                // *** End programmer edit section *** (Номенклатура.ЗащСвойст Set start)
                this.fЗащСвойст = value;
                // *** Start programmer edit section *** (Номенклатура.ЗащСвойст Set end)

                // *** End programmer edit section *** (Номенклатура.ЗащСвойст Set end)
            }
        }
        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (Номенклатура.Наименование CustomAttributes)

        // *** End programmer edit section *** (Номенклатура.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (Номенклатура.Наименование Get start)

                // *** End programmer edit section *** (Номенклатура.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (Номенклатура.Наименование Get end)

                // *** End programmer edit section *** (Номенклатура.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Номенклатура.Наименование Set start)

                // *** End programmer edit section *** (Номенклатура.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (Номенклатура.Наименование Set end)

                // *** End programmer edit section *** (Номенклатура.Наименование Set end)
            }
        }
        
        /// <summary>
        /// ЭкоКласс.
        /// </summary>
        // *** Start programmer edit section *** (Номенклатура.ЭкоКласс CustomAttributes)

        // *** End programmer edit section *** (Номенклатура.ЭкоКласс CustomAttributes)
        [StrLen(255)]
        public virtual string ЭкоКласс
        {
            get
            {
                // *** Start programmer edit section *** (Номенклатура.ЭкоКласс Get start)

                // *** End programmer edit section *** (Номенклатура.ЭкоКласс Get start)
                string result = this.fЭкоКласс;
                // *** Start programmer edit section *** (Номенклатура.ЭкоКласс Get end)

                // *** End programmer edit section *** (Номенклатура.ЭкоКласс Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Номенклатура.ЭкоКласс Set start)

                // *** End programmer edit section *** (Номенклатура.ЭкоКласс Set start)
                this.fЭкоКласс = value;
                // *** Start programmer edit section *** (Номенклатура.ЭкоКласс Set end)

                // *** End programmer edit section *** (Номенклатура.ЭкоКласс Set end)
            }
        }
        
        /// <summary>
        /// Номенклатура.
        /// </summary>
        // *** Start programmer edit section *** (Номенклатура.ГотПродукция CustomAttributes)

        // *** End programmer edit section *** (Номенклатура.ГотПродукция CustomAttributes)
        public virtual IIS.Proektirovanie2.DetailArrayOfГотПродукция ГотПродукция
        {
            get
            {
                // *** Start programmer edit section *** (Номенклатура.ГотПродукция Get start)

                // *** End programmer edit section *** (Номенклатура.ГотПродукция Get start)
                if ((this.fГотПродукция == null))
                {
                    this.fГотПродукция = new IIS.Proektirovanie2.DetailArrayOfГотПродукция(this);
                }
                IIS.Proektirovanie2.DetailArrayOfГотПродукция result = this.fГотПродукция;
                // *** Start programmer edit section *** (Номенклатура.ГотПродукция Get end)

                // *** End programmer edit section *** (Номенклатура.ГотПродукция Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Номенклатура.ГотПродукция Set start)

                // *** End programmer edit section *** (Номенклатура.ГотПродукция Set start)
                this.fГотПродукция = value;
                // *** Start programmer edit section *** (Номенклатура.ГотПродукция Set end)

                // *** End programmer edit section *** (Номенклатура.ГотПродукция Set end)
            }
        }
        
        /// <summary>
        /// Номенклатура.
        /// </summary>
        // *** Start programmer edit section *** (Номенклатура.ЗапасМатериалов CustomAttributes)

        // *** End programmer edit section *** (Номенклатура.ЗапасМатериалов CustomAttributes)
        public virtual IIS.Proektirovanie2.DetailArrayOfЗапасМатериалов ЗапасМатериалов
        {
            get
            {
                // *** Start programmer edit section *** (Номенклатура.ЗапасМатериалов Get start)

                // *** End programmer edit section *** (Номенклатура.ЗапасМатериалов Get start)
                if ((this.fЗапасМатериалов == null))
                {
                    this.fЗапасМатериалов = new IIS.Proektirovanie2.DetailArrayOfЗапасМатериалов(this);
                }
                IIS.Proektirovanie2.DetailArrayOfЗапасМатериалов result = this.fЗапасМатериалов;
                // *** Start programmer edit section *** (Номенклатура.ЗапасМатериалов Get end)

                // *** End programmer edit section *** (Номенклатура.ЗапасМатериалов Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Номенклатура.ЗапасМатериалов Set start)

                // *** End programmer edit section *** (Номенклатура.ЗапасМатериалов Set start)
                this.fЗапасМатериалов = value;
                // *** Start programmer edit section *** (Номенклатура.ЗапасМатериалов Set end)

                // *** End programmer edit section *** (Номенклатура.ЗапасМатериалов Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "НоменклатураE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View НоменклатураE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("НоменклатураE", typeof(IIS.Proektirovanie2.Номенклатура));
                }
            }
            
            /// <summary>
            /// "НоменклатураL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View НоменклатураL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("НоменклатураL", typeof(IIS.Proektirovanie2.Номенклатура));
                }
            }
        }
    }
}
