//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proektirovanie2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Перемещение.
    /// </summary>
    // *** Start programmer edit section *** (Перемещение CustomAttributes)

    // *** End programmer edit section *** (Перемещение CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПеремещениеE", new string[] {
            "Ответственный as \'Ответственный\'",
            "Контрагент as \'Контрагент\'",
            "Материалы as \'Материалы\'",
            "Цена as \'Цена\'",
            "КолВо as \'Кол во\'",
            "Сумма as \'Сумма\'",
            "Контрагенты as \'Контрагенты\'",
            "Контрагенты.ФИО as \'ФИО\'",
            "Сотрудники as \'Сотрудники\'",
            "Сотрудники.ФИО as \'ФИО\'",
            "Номенклатура as \'Номенклатура\'",
            "Номенклатура.Наименование as \'Наименование\'"}, Hidden=new string[] {
            "Контрагенты.ФИО",
            "Сотрудники.ФИО",
            "Номенклатура.Наименование"})]
    [MasterViewDefineAttribute("ПеремещениеE", "Контрагенты", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [MasterViewDefineAttribute("ПеремещениеE", "Сотрудники", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [MasterViewDefineAttribute("ПеремещениеE", "Номенклатура", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [View("ПеремещениеL", new string[] {
            "Ответственный as \'Ответственный\'",
            "Контрагент as \'Контрагент\'",
            "Материалы as \'Материалы\'",
            "Цена as \'Цена\'",
            "КолВо as \'Кол во\'",
            "Сумма as \'Сумма\'",
            "Контрагенты.ФИО as \'ФИО\'",
            "Сотрудники.ФИО as \'ФИО\'",
            "Номенклатура.Наименование as \'Наименование\'"})]
    public class Перемещение : ICSSoft.STORMNET.DataObject
    {
        
        private string fОтветственный;
        
        private string fКонтрагент;
        
        private string fМатериалы;
        
        private double fЦена;
        
        private double fКолВо;
        
        private double fСумма;
        
        private IIS.Proektirovanie2.Контрагенты fКонтрагенты;
        
        private IIS.Proektirovanie2.Сотрудники fСотрудники;
        
        private IIS.Proektirovanie2.Номенклатура fНоменклатура;
        
        // *** Start programmer edit section *** (Перемещение CustomMembers)

        // *** End programmer edit section *** (Перемещение CustomMembers)

        
        /// <summary>
        /// КолВо.
        /// </summary>
        // *** Start programmer edit section *** (Перемещение.КолВо CustomAttributes)

        // *** End programmer edit section *** (Перемещение.КолВо CustomAttributes)
        public virtual double КолВо
        {
            get
            {
                // *** Start programmer edit section *** (Перемещение.КолВо Get start)

                // *** End programmer edit section *** (Перемещение.КолВо Get start)
                double result = this.fКолВо;
                // *** Start programmer edit section *** (Перемещение.КолВо Get end)

                // *** End programmer edit section *** (Перемещение.КолВо Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Перемещение.КолВо Set start)

                // *** End programmer edit section *** (Перемещение.КолВо Set start)
                this.fКолВо = value;
                // *** Start programmer edit section *** (Перемещение.КолВо Set end)

                // *** End programmer edit section *** (Перемещение.КолВо Set end)
            }
        }
        
        /// <summary>
        /// Контрагент.
        /// </summary>
        // *** Start programmer edit section *** (Перемещение.Контрагент CustomAttributes)

        // *** End programmer edit section *** (Перемещение.Контрагент CustomAttributes)
        [StrLen(255)]
        public virtual string Контрагент
        {
            get
            {
                // *** Start programmer edit section *** (Перемещение.Контрагент Get start)

                // *** End programmer edit section *** (Перемещение.Контрагент Get start)
                string result = this.fКонтрагент;
                // *** Start programmer edit section *** (Перемещение.Контрагент Get end)

                // *** End programmer edit section *** (Перемещение.Контрагент Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Перемещение.Контрагент Set start)

                // *** End programmer edit section *** (Перемещение.Контрагент Set start)
                this.fКонтрагент = value;
                // *** Start programmer edit section *** (Перемещение.Контрагент Set end)

                // *** End programmer edit section *** (Перемещение.Контрагент Set end)
            }
        }
        
        /// <summary>
        /// Материалы.
        /// </summary>
        // *** Start programmer edit section *** (Перемещение.Материалы CustomAttributes)

        // *** End programmer edit section *** (Перемещение.Материалы CustomAttributes)
        [StrLen(255)]
        public virtual string Материалы
        {
            get
            {
                // *** Start programmer edit section *** (Перемещение.Материалы Get start)

                // *** End programmer edit section *** (Перемещение.Материалы Get start)
                string result = this.fМатериалы;
                // *** Start programmer edit section *** (Перемещение.Материалы Get end)

                // *** End programmer edit section *** (Перемещение.Материалы Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Перемещение.Материалы Set start)

                // *** End programmer edit section *** (Перемещение.Материалы Set start)
                this.fМатериалы = value;
                // *** Start programmer edit section *** (Перемещение.Материалы Set end)

                // *** End programmer edit section *** (Перемещение.Материалы Set end)
            }
        }
        
        /// <summary>
        /// Ответственный.
        /// </summary>
        // *** Start programmer edit section *** (Перемещение.Ответственный CustomAttributes)

        // *** End programmer edit section *** (Перемещение.Ответственный CustomAttributes)
        [StrLen(255)]
        public virtual string Ответственный
        {
            get
            {
                // *** Start programmer edit section *** (Перемещение.Ответственный Get start)

                // *** End programmer edit section *** (Перемещение.Ответственный Get start)
                string result = this.fОтветственный;
                // *** Start programmer edit section *** (Перемещение.Ответственный Get end)

                // *** End programmer edit section *** (Перемещение.Ответственный Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Перемещение.Ответственный Set start)

                // *** End programmer edit section *** (Перемещение.Ответственный Set start)
                this.fОтветственный = value;
                // *** Start programmer edit section *** (Перемещение.Ответственный Set end)

                // *** End programmer edit section *** (Перемещение.Ответственный Set end)
            }
        }
        
        /// <summary>
        /// Сумма.
        /// </summary>
        // *** Start programmer edit section *** (Перемещение.Сумма CustomAttributes)

        // *** End programmer edit section *** (Перемещение.Сумма CustomAttributes)
        public virtual double Сумма
        {
            get
            {
                // *** Start programmer edit section *** (Перемещение.Сумма Get start)

                // *** End programmer edit section *** (Перемещение.Сумма Get start)
                double result = this.fСумма;
                // *** Start programmer edit section *** (Перемещение.Сумма Get end)

                // *** End programmer edit section *** (Перемещение.Сумма Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Перемещение.Сумма Set start)

                // *** End programmer edit section *** (Перемещение.Сумма Set start)
                this.fСумма = value;
                // *** Start programmer edit section *** (Перемещение.Сумма Set end)

                // *** End programmer edit section *** (Перемещение.Сумма Set end)
            }
        }
        
        /// <summary>
        /// Цена.
        /// </summary>
        // *** Start programmer edit section *** (Перемещение.Цена CustomAttributes)

        // *** End programmer edit section *** (Перемещение.Цена CustomAttributes)
        public virtual double Цена
        {
            get
            {
                // *** Start programmer edit section *** (Перемещение.Цена Get start)

                // *** End programmer edit section *** (Перемещение.Цена Get start)
                double result = this.fЦена;
                // *** Start programmer edit section *** (Перемещение.Цена Get end)

                // *** End programmer edit section *** (Перемещение.Цена Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Перемещение.Цена Set start)

                // *** End programmer edit section *** (Перемещение.Цена Set start)
                this.fЦена = value;
                // *** Start programmer edit section *** (Перемещение.Цена Set end)

                // *** End programmer edit section *** (Перемещение.Цена Set end)
            }
        }
        
        /// <summary>
        /// Перемещение.
        /// </summary>
        // *** Start programmer edit section *** (Перемещение.Контрагенты CustomAttributes)

        // *** End programmer edit section *** (Перемещение.Контрагенты CustomAttributes)
        [PropertyStorage(new string[] {
                "Контрагенты"})]
        [NotNull()]
        public virtual IIS.Proektirovanie2.Контрагенты Контрагенты
        {
            get
            {
                // *** Start programmer edit section *** (Перемещение.Контрагенты Get start)

                // *** End programmer edit section *** (Перемещение.Контрагенты Get start)
                IIS.Proektirovanie2.Контрагенты result = this.fКонтрагенты;
                // *** Start programmer edit section *** (Перемещение.Контрагенты Get end)

                // *** End programmer edit section *** (Перемещение.Контрагенты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Перемещение.Контрагенты Set start)

                // *** End programmer edit section *** (Перемещение.Контрагенты Set start)
                this.fКонтрагенты = value;
                // *** Start programmer edit section *** (Перемещение.Контрагенты Set end)

                // *** End programmer edit section *** (Перемещение.Контрагенты Set end)
            }
        }
        
        /// <summary>
        /// Перемещение.
        /// </summary>
        // *** Start programmer edit section *** (Перемещение.Номенклатура CustomAttributes)

        // *** End programmer edit section *** (Перемещение.Номенклатура CustomAttributes)
        [PropertyStorage(new string[] {
                "Номенклатура"})]
        [NotNull()]
        public virtual IIS.Proektirovanie2.Номенклатура Номенклатура
        {
            get
            {
                // *** Start programmer edit section *** (Перемещение.Номенклатура Get start)

                // *** End programmer edit section *** (Перемещение.Номенклатура Get start)
                IIS.Proektirovanie2.Номенклатура result = this.fНоменклатура;
                // *** Start programmer edit section *** (Перемещение.Номенклатура Get end)

                // *** End programmer edit section *** (Перемещение.Номенклатура Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Перемещение.Номенклатура Set start)

                // *** End programmer edit section *** (Перемещение.Номенклатура Set start)
                this.fНоменклатура = value;
                // *** Start programmer edit section *** (Перемещение.Номенклатура Set end)

                // *** End programmer edit section *** (Перемещение.Номенклатура Set end)
            }
        }
        
        /// <summary>
        /// Перемещение.
        /// </summary>
        // *** Start programmer edit section *** (Перемещение.Сотрудники CustomAttributes)

        // *** End programmer edit section *** (Перемещение.Сотрудники CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудники"})]
        [NotNull()]
        public virtual IIS.Proektirovanie2.Сотрудники Сотрудники
        {
            get
            {
                // *** Start programmer edit section *** (Перемещение.Сотрудники Get start)

                // *** End programmer edit section *** (Перемещение.Сотрудники Get start)
                IIS.Proektirovanie2.Сотрудники result = this.fСотрудники;
                // *** Start programmer edit section *** (Перемещение.Сотрудники Get end)

                // *** End programmer edit section *** (Перемещение.Сотрудники Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Перемещение.Сотрудники Set start)

                // *** End programmer edit section *** (Перемещение.Сотрудники Set start)
                this.fСотрудники = value;
                // *** Start programmer edit section *** (Перемещение.Сотрудники Set end)

                // *** End programmer edit section *** (Перемещение.Сотрудники Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПеремещениеE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПеремещениеE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПеремещениеE", typeof(IIS.Proektirovanie2.Перемещение));
                }
            }
            
            /// <summary>
            /// "ПеремещениеL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПеремещениеL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПеремещениеL", typeof(IIS.Proektirovanie2.Перемещение));
                }
            }
        }
    }
}
